development:
  adapter: postgresql
  database: test
  password: test
  pool: 5
  timeout: 5000
  username: test
  host: localhost
production:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000